<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'IRSpeedyVPN' And '$(UseCosturaSingleFile)' == ''">
    <UseCosturaSingleFile>true</UseCosturaSingleFile>
  </PropertyGroup>
  <ItemGroup Condition="'$(UseCosturaSingleFile)' == 'true' And '$(MSBuildProjectName)' == 'IRSpeedyVPN'">
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all" />
    <PackageReference Include="Costura.Fody" Version="6.2.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
