<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../IRSpeedyVPN/Common/DailyLogStore.cs" Link="DailyLogStore.cs" />
    <Compile Include="../../IRSpeedyVPN/Common/LogPolicy.cs" Link="LogPolicy.cs" />
    <Compile Include="../../IRSpeedyVPN/Common/LogHelper.cs" Link="LogHelper.cs" />
  </ItemGroup>
</Project>
