<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><LangVersion>7.3</LangVersion><NoWarn>SYSLIB0014</NoWarn></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../IRSpeedyVPN/WebServices/PasswordChangeClient.cs" Link="PasswordChangeClient.cs" />
    <Compile Include="../../IRSpeedyVPN/WebServices/BaseHttpResponse.cs" Link="BaseHttpResponse.cs" />
    <Compile Include="../../IRSpeedyVPN/Models/Services/ChangePasswordResult.cs" Link="ChangePasswordResult.cs" />
    <Compile Include="../../IRSpeedyVPN/Common/Json/JsonConvertibleAttribute.cs" Link="JsonConvertibleAttribute.cs" />
    <Compile Include="../../IRSpeedyVPN/Common/Json/JsonPropertyAttribute.cs" Link="JsonPropertyAttribute.cs" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>
</Project>
