<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../IRSpeedyVPN/Services/UrlTestRetryPolicy.cs" Link="UrlTestRetryPolicy.cs" />
    <Compile Include="../../IRSpeedyVPN/Services/InitialUrlTestSchedule.cs" Link="InitialUrlTestSchedule.cs" />
    <Compile Include="../../IRSpeedyVPN/Services/Libcore/LibcoreMessages.cs" Link="LibcoreMessages.cs" />
  </ItemGroup>
</Project>
